INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Pink', '%23B1365F', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Fuchsia ', '%235C1158', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Red  ', '%23711616', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Crimson', '%23691426', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Orange', '%23BE6D00', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Orange Red', '%23B1440E', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Red Orange', '%23853104', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Burnt Orange', '%238C500B', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Brown Orange', '%23754916', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Gold ', '%2388880E', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Goldenrod', '%23AB8B00', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Darker Goldenrod', '%23856508', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Pale Green', '%2328754E', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Lighter Green', '%231B887A', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Forest Green', '%230D7813', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Olive Green', '%23528800', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Jungle Green', '%23125A12', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Another Olive', '%232F6309', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Another Green', '%232F6213', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Sea Green', '%230F4B38', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Golden Olive', '%235F6B02', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Green Gray', '%234A716C', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Olive Gray', '%236E6E41', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Dull Navy', '%2329527A', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Standard Blue', '%232952A3', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Blue Gray', '%234E5D6C', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Blue Steel', '%235A6986', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Another blue', '%23182C57', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Dark Blue', '%23060D5E', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Sea Blue', '%23113F47', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Violet', '%237A367A', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Purple', '%235229A3', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Purple Gray', '%23865A5A', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Purple Brown', '%23705770', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Deep Purple', '%2323164E', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Magenta', '%235B123B', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Another Purple', '%2342104A', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Yellow Brown', '%23875509', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Brown', '%238D6F47', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Nice Brown', '%236B3304', false);
INSERT INTO public.therapist_colour (colour_id, code, taken) VALUES ('Black', '%23333333', false);